services:
  flask_app:
    image: flask-redis
    container_name: flask-redis
    ports:
      - "80:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
